### PR TITLE
Refactor style API

### PR DESCRIPTION
**Pull request by antonok-edm**
Gigantic follow up to #67!

I'm sure this will entail a lot of review either way, but here are some things to note:
- I used cargo workspaces to split up the crates, which I figured was the best solution for any "core" functionality (e.g., it's good to at least keep a reference CSS parser and probably eventually an XML parser as well, just to make it easier for new users). If you'd prefer to have them separated out into different repositories under the maps4print namespace, just set those up and I'll push to them.
- I ended up splitting out the native styles into a separate crate as well. They didn't fit very well in either crate, and I imagine there could be some more complex functionality there in the future (e.g., reading and parsing from a GTK or Qt theme could also be considered a "native" style, or maybe some users would want a Windows style on MacOS for whatever reason).
- I lifted all of the hot-reloading logic out of the `AppStyle` struct (previously the `Css` struct) and moved it into `Window`. That way it's also kept out of the public API, which keeps things slightly cleaner. Two new `Window` constructors allow you to pass a `HotReloadable` reference, and, optionally, a hot-reload interval if 500ms is too fast or slow for your computer.
- Because we now hold a reference to a `HotReloadable` trait object, it must have a lifetime longer than the `App` object. Generally, this means it must be created first, at least until NLL is implemented. I switched the order of declarations in most of the tests, but you can see what I mean in `table.rs`, where I actually added a `#![feature(nll)]` attribute with a comment. The alternative (since it's a dynamic reference) would be requiring users to `Box` it before passing it to azul. I chose the first version because hopefully there's a fix coming soon for the language itself, but let me know if you have other opinions or ideas.

### CODE REVIEW

**Comment by fschutt** [comment]
- The main part of this PR is simply renaming everything with "CSS" to "AppStyle, which is a bad idea. Please don't rename `Css` to `AppStyle` or `css*` to `style*`, azul is clearly based on `Css`, all properties are based on CSS counterparts, selector matching is based on CSS, `AppStyle` is longer, less memorable and less descriptive overall. Even if the source format differs, it's still a *cascading* style sheet after all.

- Rename `HotReloadable` to `HotReloadHandler` and use a `Box<HotReloadHandler>` - there is no benefit in wrangling with lifetimes here, it just makes things more complex. The dynamic dispatch is there anyways, and a single `Box` allocation is not performance-intensive, esp. since it's only active in debug mode. This also solves your NLL issues.

- `reload_style()` should be able to return a string as an error (this is the one place where returning a string as an error is a good idea, because the error needs to be printed during hot-reloading). Otherwise, external style handlers are not able to print custom error messages during hot reloading.

- Splitting out the native CSS into a seperate crate is generally a good idea, but I don't want people having to import 3 crates just to get started. Simply re-export the crates in a seperate module:

```rust
// -- azul_native_style/lib.rs
use azul::Css;
use azul_css::parse_from_string;

fn get_native_css() -> Css {
   parse_from_string(WINDOWS_CSS).unwrap();
}

// -- azul_css/lib.rs:
#[cfg(feature = "native_css")] // should be enabled by default
use azul::Css;

fn parse_from_string(str: &str) -> Result<Css, ParseError> { /* parser here */ }

// -- azul/css.rs
impl Css {
     #[cfg(feature = "azul_css/native_css")]
     pub fn native() -> Self { ::azul_css::get_native_css() }

     #[cfg(feature = "azul_css")]
     pub fn from_str(input: &str) -> Result<Css, ParseError> { ::azul_css::parse_from_string(input) }

     #[cfg(feature = "azul_css")]
    pub fn hot_reload(file_path: &str) -> Box<HotReloadHandler> {
        Box::new(::azul_css::CssHotReloadHandler { file_path })
    }

     #[cfg(feature = "azul_css/native_css")]
    pub fn hot_reload_override_native(file_path: &str) -> Box<HotReloadHandler> {
        Box::new(::azul_css::CssNativeHotReloadHandler { file_path })
    }
}
```
... so that this code still works:

```rust
use azul::css::*;

let css = Css::from_str("");
let css2 = Css::native();
let css3 = Css::hot_reload("path");
let css4 = Css::hot_reload_override_native("path");
```

Because then you can disable the CSS parser if you don't need it (i.e. if you construct your style from JSON for whatever reason, you don't necessarily need to have a CSS parser). Otherwise, all crates would need to depend on `azul_css` directly.

The goal of this PR was to move the azul_css parser out, so that parsing is optional and reusable, but that doesn't mean that the final library user has to directly depend on `azul_css`.

I know, your main work was to rename `Css` to `AppStyle`, and that a lot of work was now done for nothing, but I really don't want to randomly rename things that shouldn't be renamed. Whatever your external handler is, it has to "compile to" a CSS-like target, since that's what azuls properties are built upon.

**Comment by fschutt** [comment]
Also - this is just a git thing - I'd rather rebase rather than pull from origin. Otherwise you end up with hundreds of small `Merge from xxx` commits. These commits are fairly useless, so rather rebase, not pull. 

And this is just a nitpicky style thing, but it would be nice if the commit messages started with a capital letter, like in regular English. They don't have to be all-lowercase. You can use `rebase -i HEAD` to edit the commit messages in bulk.

**Comment by antonok-edm** [comment]
* My original intention was not to change names around until I heard your opinion on it, but I found that it was actually really hard to tell where the boundary between datatypes and parsing logic was until I did it. On the one hand, I think the way it is split up now is functionally solid, so it wouldn't be particularly difficult to switch it back. On the other hand, I'm a little concerned that things may start to blur back together and become confusing again. I agree that simply renaming things from `css*` to `style*` didn't feel like the best solution; it was the best I could come up with at the time. But I do think there should be some distinction in nomenclature between the datatypes representing a style and those used for parsing a CSS file. Do you have any other ideas? From my perspective, at least, CSS refers to an established standard with well-defined syntax; syntax which doesn't define things like `vec![CssDeclaration { ... }]`.

* Not sure if you were aiming for backward compatibility with the old `hot_reload` and `hot_reload_override_native` functions -- you got the return types right in the function signatures so it's unclear. But it won't be possible to use them the same way as before, since the `HotReloadHandler` is now a distinct type from the style, and gets passed as a separate argument to `Window::new`.

* I don't think the re-exports as you've described them will be possible, because it will create cyclic dependencies (`azul-native-style` and `azul-css` both already depend on `azul` for style datatypes). Potentially we could make something like `azul-simple` which re-exports azul's datatypes, native styles, CSS parsing, and XML parsing when it's done, resulting in a single import for complete beginners. But I'm not even sure if that is significantly simpler.

**Comment by antonok-edm** [comment]
Starting to converge, I think. I ended up making the hot-reload logic a lot cleaner. Anything else you want changed?

Also, are those CI failures my fault? I can't tell exactly what's wrong from the tracebacks, but I don't think I changed anything relevant to what they're pointing out.

**Comment by fschutt** [comment]
Yeah, well please just keep the old names with the "Css" instead of "AppStyle" everywhere. It's a CSS parser, not a "style parser", etc. - `azul-css` instead of `azul-style`. Don't rename `CssPath` to `XPath` - it's not an XPath, it's a CSS selector, these are different things. I'll have to go over it later, but my main problem is that it's still "AppStyle" everywhere.

**Comment by antonok-edm** [comment]
Sorry, I interpreted

> As for the naming... I'd just leave it as-is for now

from my own `HEAD`. I switched it back.

**Comment by fschutt** [comment]
Thanks - looks good so far, I'll take a look tomorrow.

**Comment by fschutt** [comment]
Yeah, you might need to rebase, I heavily refactored the CSS module yesterday. Azul now has full CSS path matching (even with `>` operators and proper specificity / inheritance rules).

**Comment by antonok-edm** [comment]
Man, that was a gigantic rebase. Should be all set now.

**Comment by fschutt** [comment]
Yeah sorry for messing up your PR, it's just that I didn't have internet yesterday and decided that I could do all the boring refactoring offline - the timing was a bit bad, but the DOM needs to be split into hierarchy and content in order to prepare :focus selectors and focus tracking.

The PR itself looks good to me, I mean, most of it is just putting existing code into different files, there's not much to critique about it. The CI failures are likely because you forgot to put the proper features in the Cargo.toml, but I can fix that after merging. So for now, the tests will "fail", but that's ok, it doesn't affect the functionality. And the examples on the website and wiki should be updated, but that's on me.

The next steps would be to seperate out the DOM and the `Layout` trait into seperate crates (because these things are necessary to write plugins), so that plugin-writers don't have to depend on the entire crate when all they need is the `Dom` and `Layout` type. And later on, layout should also be seperated, to allow for SVG / PDF / PostScript rendering backends (for example, for PDF viewers / printing / etc.).

Thanks for doing this PR, although it's just "cleanup", it does help a lot.

**Pull request merged**
