### PR TITLE
Refactor system font loading

### LINKED ISSUE #65: UI blank and renders only after resize/click
## Description

When trying out the examples on my machine, I noticed that reproducibly  the UI only shows after I force a redraw by resizing the window or clicking somewhere inside it.

## Version / OS

* azul version:
version = "0.1.0"
source = "git+https://github.com/maps4print/azul#2068541297c8345b622a8a05c5e0ac690d1c154e"

* Operating system:
Linux Ubuntu 16.04

* Windowing system (X11 or Wayland, Linux only):
X11

* Rust:
rustc 1.30.1 (1433507eb 2018-11-07)

## Steps to Reproduce

* Create a new cargo project with azul as dependency.
* paste one of the azul examples in main.rs
* `cargo run`

## Expected Behavior
The window opens and immediately shows the rendered example.

## Actual Behavior
The window is empty and only redraws the example when resizing the window or clicking somewhere.

screenshot from 2018-11-25 12-25-03

After clicking:
screenshot from 2018-11-25 12-25-23

### PR DESCRIPTION
**Pull request by antonok-edm**
Fixes #65 for real this time -- I tried it out on the list, scroll_list, calculator, and game_of_life examples in both debug and release mode.

Essentially, all the font data in `app_resources.rs` was wrapped in `RefCell<Rc<_>>`, which made it really hard to reason about ownership. Consequently, system fonts would be loaded for the first time from an immutable binding in the render loop. This PR makes azul scan through the provided `Css` at startup or on hot-reload events and attempt to load system fonts as necessary.

I removed the distinction between "builtin" and "external" fonts, since the difference was really nuanced in the first place. The datatypes were the same, it just boiled down to semantics of "attempt to load this from the system" or "don't", which can already be achieved by using `app.add_font()` anyways. The "builtin" naming also seems to imply they come packaged with azul, which can be confusing. Instead, all `FontId`s are now just identifiers like `CssImageId`, and I added the `system_fonts` feature (enabled by default) that makes azul attempt to load fonts from the system if they're not already available as a resource.

While making this PR, I came up with a few other considerations for the future, which should be compatible with the new model:

* It should eventually be possible to load resources by callback at runtime, for e.g. loading new images in graphical design apps or fonts in WYSIWYG text editors.

* It should be possible to embed resources alongside rules in the `Css`. Background textures and fonts are definitely a part of an application's style, and the CSS standard supports the same concept with `@font-face` and `src: data(...)`.

### CODE REVIEW

**Comment by fschutt** [comment]
> I removed the distinction between "builtin" and "external" fonts, since the difference was really nuanced in the first place. 

No, the distinction was very important for graphical design apps - I need to be sure that when I load a font file, I can load a specific font file, and only that, i.e. create a new, unique FontId for a specific font file, independent of the system resources. There are situations where you don't want to load any system fonts, and rather error out if the font isn't found rather than trying to fall back on system fonts.

> and I added the system_fonts feature (enabled by default) that makes azul attempt to load fonts from the system if they're not already available as a resource.

This is a bad idea, that's exactly what I wanted to avoid with the ExternalFont and why I made the distinction in the first place. There are times where you have to be absolutely sure that a certain font (file) is used and the font is *not* loaded from the system (but I still want the option to load fonts from the system in other parts of my code). Basically the FontId::External does not have to be the font name, it almost never is (in my code, it's usually the file name / file path to the font). It can be some kind of auto-generated string or auto-generated ID - I need to make sure that the Font isn't loaded from the system.

> This PR makes azul scan through the provided Css at startup or on hot-reload events and attempt to load system fonts as necessary.

But what if someone adds a font in a callback, outside of the CSS? Then your code wouldn't scan for it. Right now it scans on every display list construction / display list uploaded - which isn't even a performance problem, so I don't see why it should be changed.

> It should be possible to embed resources alongside rules in the Css.

Why - just because CSS has that feature? It's not good practice to do this in CSS, and if you want to load a certain binary blob, you can simply all your fonts / images before calling `app.run()`, and then use the CSS IDs. The only reason for CSS to have that feature is to avoid additional network requests for small resources, which isn't a problem in azul. Why should `data(...)` be implemented?

> It should eventually be possible to load resources by callback at runtime

You can do that already, every callback gets passed a `&mut AppState` as the first argument, and the `AppState` contains the `AppResources`, so you can add font and image resources in the callback without any problems. That's exactly why the callback gets passed a `&mut AppState<T>` and not a `&mut T`.

I'll look over the PR later, but overall it's a bad idea - the distinction exists for a reason.

**Comment by antonok-edm** [comment]
> No, the distinction was very important for graphical design apps - I need to be sure that when I load a font file, I can load a specific font file, and only that, i.e. create a new, unique FontId for a specific font file, independent of the system resources. There are situations where you don't want to load any system fonts, and rather error out if the font isn't found rather than trying to fall back on system fonts.

I can have it error out instead, that is not a big difference.

> This is a bad idea, that's exactly what I wanted to avoid with the ExternalFont and why I made the distinction in the first place. There are times where you have to be absolutely sure that a certain font (file) is used and the font is not loaded from the system (but I still want the option to load fonts from the system in other parts of my code). Basically the FontId::External does not have to be the font name, it almost never is (in my code, it's usually the file name / file path to the font). It can be some kind of auto-generated string or auto-generated ID - I need to make sure that the Font isn't loaded from the system.

That's exactly what the FontId is now - just a `String`; it could be any string. You can just give it a hash of the font contents and system time and be absolutely sure it's not loading a font from the system. If there's no font installed with that name, it will currently just be ignored -- but as I said earlier, I can have it error out if that's preferable.

> But what if someone adds a font in a callback, outside of the CSS? Then your code wouldn't scan for it. Right now it scans on every display list construction / display list uploaded - which isn't even a performance problem, so I don't see why it should be changed.

As you can probably guess, I didn't realize that was already possible. You're right that the code I added wouldn't scan for it, but I did write it with that future requirement in mind -- I can look into adding it now if you'd like. I changed it because it works against the borrow checker with all the `RefCell<Rc<>>` usage to make updates to immutable data, which makes the code a lot harder to work with. I wasn't particularly motivated by performance, so I didn't do any benchmarking, but my hunch is that this should be slightly better in that regard.

> Why - just because CSS has that feature? It's not good practice to do this in CSS, and if you want to load a certain binary blob, you can simply all your fonts / images before calling app.run(), and then use the CSS IDs. The only reason for CSS to have that feature is to avoid additional network requests for small resources, which isn't a problem in azul. Why should data(...) be implemented?

I probably should have explained that a little better -- as an extreme example, maybe somebody wants to make an `azul-windows95-style` crate. Chances are, most users don't have the necessary fonts installed on their systems, and things like titlebars might need their own custom graphics for backgrounds.

**Comment by fschutt** [comment]
Yeah, I get what you're trying to do and I agree that the current font loading is too complex. So basically, there could be two different functions: One for loading a font that errors if it can't find the font, and one that doesn't and searches the system for the font.

I'll have a look tomorrow.

**Comment by antonok-edm** [comment]
Quick update:

Turns out dynamic style overrides didn't need any extra changes for explicitly loaded font resources, since they now work through the same mechanism as normal font loading. Finding system fonts just involved traversing the `Dom` for nodes with dynamic style overrides for a font-family property. Those now get loaded as expected, too.

I intend to add something like a system font viewer example tomorrow, where a user can enter a font name in a text box and have some other text displayed using that font, if it's found.

**Comment by fschutt** [comment]
Well, while I don't think putting the fonts on the DOM nodes is a good idea, I have a better idea for loading fonts. The real problem with fonts isn't when to add them, that's fairly easy, just scan the display list for any fonts that aren't uploaded yet. The problem is when it's safe to remove them (unload the font from memory). Because you can't just add and remove a font on every frame, so you need to have the font at least loaded in memory at all times in the current system.

However, that's not how things work in reality as a font is either:

- included directly in the binary
- backed on disk
- loaded from the network
- loaded from a system font

So my idea was to make that more expressive by simply having something like:

```rust
enum FontSource {
    InBinary(&'static [u8]),
    FontPath(String),
    SystemFont(String),
    LoadedFromNetwork(Url),
}
```

The reason for doing this is to control when a font is loaded / unloaded - because loading fonts can use up a lot of memory (often a few megabytes just for one font). So if a font is offscreen or is currently unused, there could be some kind of "garbage collection" that cleans up the unused fonts. I.e.:

```rust
currently_loaded_fonts: HashMap<FontId, FontSource>
```

This way, it would be possible to unload the font binary data, but if the ID is then used again, at least the framework knows where to look for the font data bytes. This way we could unload the font bytes from memory, while still keeping the option to re-add the font when needed.

This was just my idea - btw, for something like a `azul-windows95-style` crate, I wouldn't want the crate to randomly add fonts in the CSS (regarding the support of `data`). If someone wants to use the `azul-windows95-style`, then the application programmer should be aware that the CSS requires a certain font. So, the programmer of the `azul-windows95-style` crate can package his font with his libary using `include_bytes!` and then the final application needs to manually add it to the app resources, making it more explicit where the fonts come from.

In the next few days I'll be doing a lot of refactoring, so it's likely that your PR will break multiple times and as I said, I do have a different system in mind for loading / unloading fonts and images and refactoring the whole ID system. I'll see if I can use this PR and / or how it could be done properly.

PS: I went over your hot-reloading API again and noticed that you've done a lot of `format!("{}", blah).to_string()` - `format!()` already returns a String, there's no need for the to_string(), just wanted to say that. I've also noticed that you use a lot of for loops with if statements in them - try using `.filter()` and `.filter_map` more!

**Comment by fschutt** [comment]
Alright I'm closing this because this is now fixed - Azul now scans the DOM on every frame and inserts the fonts and submits them to the renderer *before* constructing a display list, which fixes this issue more cleanly. Azul can also now delete font immediately when they aren't used anymore. This is a more stable (and more memory-friendly) solution than requiring the user to call add_font and delete_font all the time. Overall that works better than this PR, since now users don't have to care anymore about where their fonts come from - but you were right that distinguishing between system / custom fonts isn't necessary. Thanks for your contribution!

**Pull request closed without merging**
