### PR TITLE
Changed font-family loading

### LINKED ISSUE #18: Panic running debug example on mac
I get a panic running the debug example. Rust 1.29.2, macOS 10.12.6

```
[ERROR][azul::logging] We are sorry, an unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: libcore/option.rs at line 345 in thread main

Error information:
called `Option::unwrap()` on a `None` value

Backtrace:

backtrace::backtrace::trace @ mod.rs:42
backtrace::capture::Backtrace::new_unresolved @ capture.rs:88
backtrace::capture::Backtrace::new @ capture.rs:63
azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:84
core::ops::function::Fn::call @ function.rs:73
std::panicking::rust_panic_with_hook @ panicking.rs:479
std::panicking::continue_panic_fmt @ panicking.rs:390
 @ panicking.rs:325
core::panicking::panic_fmt @ panicking.rs:77
core::panicking::panic @ panicking.rs:52
<core::option::Option<T>>::unwrap @ macros.rs:20
debug::my_button_click_handler @ debug.rs:150
azul::app::do_hit_test_and_call_callbacks::{{closure}} @ app.rs:723
azul::app::do_hit_test_and_call_callbacks @ app.rs:735
<azul::app::App<T>>::run_inner @ app.rs:234
<azul::app::App<T>>::run @ app.rs:192
debug::main @ debug.rs:235
std::rt::lang_start::{{closure}} @ rt.rs:74
std::panicking::try::do_call @ panicking.rs:310
 @ lib.rs:105
std::rt::lang_start_internal @ panicking.rs:289
std::rt::lang_start @ rt.rs:74

```

### PR DESCRIPTION
**Pull request by Yatekii**
Fixes #18 

If multiple fonts are specified in the CSS it will load
the first existing font-family, not just the first one.

`AppResources::get_builtin_font()` now takes a comma separated
string too to load any of a list of fonts

Changed the default font-families for OSX to "Arial, Helvetica"

### CODE REVIEW

**Comment by fschutt** [comment]
@Yatekii Right, could you fix the CI errors? Also, the `error!` macro that you've used should be wrapped in a `#[cfg(feature = "logging")] { error!("the error"); }` - since logging is optional, it'll probably fail that CI test.

**Comment by Yatekii** [comment]
Yep, I fixed all the things. Hopefully.
Sorry I didn't see that I should check for the logging feature at first glance. Thx for the hint.

**Comment by Yatekii** [comment]
Pretty sure this wouldn't compile anymore, considering all the stuff you changed ;)

**Comment by fschutt** [comment]
I have added font-family fallback loading on the master branch, however I haven't tested it yet. The main problem why I never merged this PR is because the font was not reliably cached. The master branch should now have font fallback loading and the font is now identified via the postscript name.

I am closing this PR because it is extremely old. Sorry for the wasted time.

**Pull request closed without merging**
