### PR TITLE
Fixes travis build

### PR DESCRIPTION
**Pull request by VictorKoenders**
- Rust 1.31 does not support:
  - creating `Self` instances (stabilized in 1.32)
  - importing dependencies `as _` (stabilized in 1.33)
- Pinned linux on ubuntu 16, because servo-fontconfig-sys requires fontconfig=2.11.1 and that's not available on ubuntu 14
- Enabled osx
- Fixed an issue in an example

### CODE REVIEW

**Comment by VictorKoenders** [comment]
Travis doesn't seem to trigger so here's the build on my repo:
https://travis-ci.org/VictorKoenders/azul/builds/554960503

**Comment by VictorKoenders** [comment]
Ah the travis build does trigger, it just doesn't show up in PR's
https://travis-ci.org/maps4print/azul/builds/554963411

**Comment by fschutt** [comment]
Yeah, I'd rather bump the requirement to rust 1.33 instead and leave the code as is, because at some point, I'll have to upgrade the code anyway. So it's better to upgrade the compiler version - sure, that makes it less compatible with older compilers, but in the future I'd have to upgrade the code anyway.

The rest is okay, but I'm not sure what the point of enabling osx is if it's also marked under "allow_failures", because then it just increases the time you have to wait for Travis. I'd add osx, but remove it from "allow_failures".

**Comment by VictorKoenders** [comment]
Bumped minimum requirement to 1.33

**Pull request merged**
