### PR TITLE
Many build&test fixes (full appveyor CI build)

### PR DESCRIPTION
**Pull request by NNemec**
Various fixes necessary to get all the appveyor CI build&test running again:
* fix builds for all examples (runtime-behavior still broken)
* fix all unit tests & doc tests
* only layout_tests remains deactivated in CI build, will need more work

All changes done carefully but without deep understanding of the history. Please review carefully.

### CODE REVIEW

**Comment by fschutt** [comment]
Well, I've had a look, but I'm currently not merging it, because the commits simply "fix" the errors by commenting them out or prefixing unused variables with underscores. They're not proper, actual bug fixes, the changes just silence the compiler warnings. I'll have to review which parts I can merge.

**Comment by NNemec** [comment]
I'll withdraw this pull request, make a careful review myself and then set up a new request. I did each change quite carefully to fix the actual problem as well as possible, but with the understanding that I have aquired over the past few days, I can probably improve this further.

**Comment by fschutt** [comment]
Well, it's just that I don't have much time to review it atm, so it might take a few days to be merged. But please don't just supress errors or warnings, I often leave them in intentionally so I know what still needs to be done.

**Comment by NNemec** [comment]
I fully agree with your approach to warnings. All my patches are intended to properly address the issue to the best of my understanding. Actually, after careful review, I found just a few details to improve:

* I removed two debatable patches containing non-obvious warning fixes (in fact, I already have more substantial fixes for both areas in the pipeline, so I'll submit them with a future request.)

* One of the function arguments I prefixed with _ turned out to be completely unnecessary, so I removed it at both call sites. The other places where I used _ were actually the proper way to deal with the situation: required but unused placeholder arguments for match espressions.

With that, I'm reopening this pull request and hope that the changes will stand up to your scrutiny.

**Pull request closed without merging**
