### PR TITLE
Fixed Calculator example.

### PR DESCRIPTION
**Pull request by DataTriny**
Hello and thank you for this nice framework!

Here is my small contribution to demonstrate how you can create a complete application using Azul. The logic for all the calculator buttons have been implemented. I can't get the app to panic, but I haven't tested it that much. Feel free to change the design of the expression div (as I am visually impaired), it may be misplaced.

### CODE REVIEW

**Comment by Serdnad** [comment]
Haha, I was working on this too, but your version with the expression history is much nicer. For some reason though, it seems like everything's getting inverted (becoming negative) when I tried it out?

**Comment by diogox** [comment]
Great initiative, but there seems to be an issue. When I click "3", "x" and "3", it shows up in the history (the upper part of the screen) as "-3x-3". I haven't really looked at the code, just though I'd point that out. 

imagem

**Comment by DataTriny** [comment]
Didn't notice before pushing, but it looks like cargo fmt broke something in window.rs. Can't get it to compile anymore...

**Comment by fschutt** [comment]
I mean it's fine I guess, but could you please revert the changes related to `cargo fmt` and focus the PR only on the calculator? The new formatting, while more consistent, is harder to read than the old one in many cases, which is why I don't like to use automated formatting.

I.e. instead of:

```rust
format!("{}, {}, {}", a, b, c);
let x = thing.map(|a| a.b()).and_then(|b| b.inner());
```

you now have things like:

```rust
format!("{}, {}, {}", 
        a, 
        b, 
        c);

let x = thing
        .map(|a| a.b())
        .and_then(|b| b.inner());
```

I mean it just increases the line count, but doesn't really add anything beyond that in terms of readability.

**Pull request closed without merging**
